/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.androhid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow_down=0x7f020000;
        public static final int arrow_down_double=0x7f020001;
        public static final int arrow_left=0x7f020002;
        public static final int arrow_right=0x7f020003;
        public static final int arrow_up=0x7f020004;
        public static final int arrow_up_double=0x7f020005;
        public static final int btn_dial_normal=0x7f020006;
        public static final int btn_dial_normal_green=0x7f020007;
        public static final int btn_dial_pressed=0x7f020008;
        public static final int btn_dial_selected=0x7f020009;
        public static final int cross=0x7f02000a;
        public static final int ic_tab_player=0x7f02000b;
        public static final int ic_tab_player_selected=0x7f02000c;
        public static final int ic_tab_player_unselected=0x7f02000d;
        public static final int ic_tab_presenter=0x7f02000e;
        public static final int ic_tab_presenter_selected=0x7f02000f;
        public static final int ic_tab_presenter_unselected=0x7f020010;
        public static final int ic_tab_video=0x7f020011;
        public static final int ic_tab_video_selected=0x7f020012;
        public static final int ic_tab_video_unselected=0x7f020013;
        public static final int icon=0x7f020014;
        public static final int icon_small=0x7f020015;
        public static final int player_button_bg=0x7f020016;
        public static final int player_end=0x7f020017;
        public static final int player_f1=0x7f020018;
        public static final int player_f2=0x7f020019;
        public static final int player_f3=0x7f02001a;
        public static final int player_fwd=0x7f02001b;
        public static final int player_mute=0x7f02001c;
        public static final int player_pause=0x7f02001d;
        public static final int player_play=0x7f02001e;
        public static final int player_rew=0x7f02001f;
        public static final int player_start=0x7f020020;
        public static final int player_stop=0x7f020021;
        public static final int player_volume_minus=0x7f020022;
        public static final int player_volume_plus=0x7f020023;
        public static final int playlist=0x7f020024;
        public static final int presenter_bookmarks=0x7f020025;
        public static final int presenter_button_bg=0x7f020026;
        public static final int presenter_button_one=0x7f020027;
        public static final int presenter_delete=0x7f020028;
        public static final int presenter_fullscreen=0x7f020029;
        public static final int presenter_preferences=0x7f02002a;
        public static final int presenter_refresh=0x7f02002b;
        public static final int screen=0x7f02002c;
        public static final int system=0x7f02002d;
    }
    public static final class id {
        public static final int CONNECT=0x7f060013;
        public static final int DISCONNECT=0x7f060014;
        public static final int INFO=0x7f060012;
        public static final int PREFERENCES=0x7f060010;
        public static final int SEARCH_DEVICE=0x7f060011;
        public static final int TextView01=0x7f060000;
        public static final int eight=0x7f060009;
        public static final int eleven=0x7f06000c;
        public static final int five=0x7f060006;
        public static final int four=0x7f060005;
        public static final int nine=0x7f06000a;
        public static final int one=0x7f060002;
        public static final int player=0x7f060001;
        public static final int presenter=0x7f06000e;
        public static final int scan=0x7f060015;
        public static final int seven=0x7f060008;
        public static final int six=0x7f060007;
        public static final int ten=0x7f06000b;
        public static final int three=0x7f060004;
        public static final int twelve=0x7f06000d;
        public static final int two=0x7f060003;
        public static final int video=0x7f06000f;
    }
    public static final class layout {
        public static final int bt_device_picker=0x7f030000;
        public static final int main=0x7f030001;
        public static final int player_tab=0x7f030002;
        public static final int preferences=0x7f030003;
        public static final int presenter_tab=0x7f030004;
        public static final int video_tab=0x7f030005;
    }
    public static final class menu {
        public static final int options_menu_main=0x7f050000;
        public static final int options_menu_scan_devices=0x7f050001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int bluetooth_not_enabled=0x7f040010;
        public static final int bt_device_search_list=0x7f040009;
        public static final int connection_established_to=0x7f040008;
        public static final int connection_failed=0x7f040007;
        public static final int connection_message=0x7f040006;
        public static final int copyright_dialog=0x7f040015;
        public static final int copyright_dialog_title=0x7f040014;
        public static final int device_picker_title=0x7f040011;
        public static final int enable_bluetooth=0x7f04000b;
        public static final int menu_button_connect=0x7f040001;
        public static final int menu_button_disconnect=0x7f040002;
        public static final int menu_button_info=0x7f040003;
        public static final int menu_button_search_device=0x7f040004;
        public static final int menu_button_settings=0x7f040005;
        public static final int no=0x7f04000e;
        public static final int no_devices=0x7f04000a;
        public static final int no_root_permission_dialog=0x7f040013;
        public static final int no_root_permission_title=0x7f040012;
        public static final int ok=0x7f04000c;
        public static final int option_menu_scan_devices_button=0x7f04000f;
        /** preference strings
         */
        public static final int preferences_title=0x7f040016;
        public static final int settings_display=0x7f04001a;
        public static final int settings_enable_track_ball_summary=0x7f04001f;
        public static final int settings_enable_track_ball_title=0x7f04001e;
        public static final int settings_key_mapping=0x7f040022;
        public static final int settings_keycode=0x7f040026;
        public static final int settings_keycode_summary=0x7f040027;
        public static final int settings_map_track_ball_summary=0x7f040021;
        public static final int settings_map_track_ball_title=0x7f040020;
        public static final int settings_modifier=0x7f040028;
        public static final int settings_modifier_summary=0x7f040029;
        public static final int settings_rotate_screen_summary=0x7f04001c;
        public static final int settings_rotate_screen_title=0x7f04001b;
        public static final int settings_stay_screen_on=0x7f040017;
        public static final int settings_stay_screen_on_summary=0x7f040019;
        public static final int settings_stay_screen_on_title=0x7f040018;
        public static final int settings_tab_player=0x7f040023;
        public static final int settings_tab_player_button_1=0x7f04002a;
        public static final int settings_tab_player_button_10=0x7f040033;
        public static final int settings_tab_player_button_11=0x7f040034;
        public static final int settings_tab_player_button_12=0x7f040035;
        public static final int settings_tab_player_button_2=0x7f04002b;
        public static final int settings_tab_player_button_3=0x7f04002c;
        public static final int settings_tab_player_button_4=0x7f04002d;
        public static final int settings_tab_player_button_5=0x7f04002e;
        public static final int settings_tab_player_button_6=0x7f04002f;
        public static final int settings_tab_player_button_7=0x7f040030;
        public static final int settings_tab_player_button_8=0x7f040031;
        public static final int settings_tab_player_button_9=0x7f040032;
        public static final int settings_tab_presenter=0x7f040025;
        public static final int settings_tab_presenter_button_1=0x7f040042;
        public static final int settings_tab_presenter_button_10=0x7f04004b;
        public static final int settings_tab_presenter_button_11=0x7f04004c;
        public static final int settings_tab_presenter_button_12=0x7f04004d;
        public static final int settings_tab_presenter_button_2=0x7f040043;
        public static final int settings_tab_presenter_button_3=0x7f040044;
        public static final int settings_tab_presenter_button_4=0x7f040045;
        public static final int settings_tab_presenter_button_5=0x7f040046;
        public static final int settings_tab_presenter_button_6=0x7f040047;
        public static final int settings_tab_presenter_button_7=0x7f040048;
        public static final int settings_tab_presenter_button_8=0x7f040049;
        public static final int settings_tab_presenter_button_9=0x7f04004a;
        public static final int settings_tab_video=0x7f040024;
        public static final int settings_tab_video_button_1=0x7f040036;
        public static final int settings_tab_video_button_10=0x7f04003f;
        public static final int settings_tab_video_button_11=0x7f040040;
        public static final int settings_tab_video_button_12=0x7f040041;
        public static final int settings_tab_video_button_2=0x7f040037;
        public static final int settings_tab_video_button_3=0x7f040038;
        public static final int settings_tab_video_button_4=0x7f040039;
        public static final int settings_tab_video_button_5=0x7f04003a;
        public static final int settings_tab_video_button_6=0x7f04003b;
        public static final int settings_tab_video_button_7=0x7f04003c;
        public static final int settings_tab_video_button_8=0x7f04003d;
        public static final int settings_tab_video_button_9=0x7f04003e;
        public static final int settings_track_ball_usage=0x7f04001d;
        public static final int tab_player_button_10_keycode_default=0x7f040060;
        public static final int tab_player_button_10_modifier_default=0x7f040061;
        public static final int tab_player_button_11_keycode_default=0x7f040062;
        public static final int tab_player_button_11_modifier_default=0x7f040063;
        public static final int tab_player_button_12_keycode_default=0x7f040064;
        public static final int tab_player_button_12_modifier_default=0x7f040065;
        /**  Default Mappings Player Tab 
         */
        public static final int tab_player_button_1_keycode_default=0x7f04004e;
        public static final int tab_player_button_1_modifier_default=0x7f04004f;
        public static final int tab_player_button_2_keycode_default=0x7f040050;
        public static final int tab_player_button_2_modifier_default=0x7f040051;
        public static final int tab_player_button_3_keycode_default=0x7f040052;
        public static final int tab_player_button_3_modifier_default=0x7f040053;
        public static final int tab_player_button_4_keycode_default=0x7f040054;
        public static final int tab_player_button_4_modifier_default=0x7f040055;
        public static final int tab_player_button_5_keycode_default=0x7f040056;
        public static final int tab_player_button_5_modifier_default=0x7f040057;
        public static final int tab_player_button_6_keycode_default=0x7f040058;
        public static final int tab_player_button_6_modifier_default=0x7f040059;
        public static final int tab_player_button_7_keycode_default=0x7f04005a;
        public static final int tab_player_button_7_modifier_default=0x7f04005b;
        public static final int tab_player_button_8_keycode_default=0x7f04005c;
        public static final int tab_player_button_8_modifier_default=0x7f04005d;
        public static final int tab_player_button_9_keycode_default=0x7f04005e;
        public static final int tab_player_button_9_modifier_default=0x7f04005f;
        public static final int tab_presenter_button_10_keycode_default=0x7f040090;
        public static final int tab_presenter_button_10_modifier_default=0x7f040091;
        public static final int tab_presenter_button_11_keycode_default=0x7f040092;
        public static final int tab_presenter_button_11_modifier_default=0x7f040093;
        public static final int tab_presenter_button_12_keycode_default=0x7f040094;
        public static final int tab_presenter_button_12_modifier_default=0x7f040095;
        /**  Default Mappings Presenter Tab 
         */
        public static final int tab_presenter_button_1_keycode_default=0x7f04007e;
        public static final int tab_presenter_button_1_modifier_default=0x7f04007f;
        public static final int tab_presenter_button_2_keycode_default=0x7f040080;
        public static final int tab_presenter_button_2_modifier_default=0x7f040081;
        public static final int tab_presenter_button_3_keycode_default=0x7f040082;
        public static final int tab_presenter_button_3_modifier_default=0x7f040083;
        public static final int tab_presenter_button_4_keycode_default=0x7f040084;
        public static final int tab_presenter_button_4_modifier_default=0x7f040085;
        public static final int tab_presenter_button_5_keycode_default=0x7f040086;
        public static final int tab_presenter_button_5_modifier_default=0x7f040087;
        public static final int tab_presenter_button_6_keycode_default=0x7f040088;
        public static final int tab_presenter_button_6_modifier_default=0x7f040089;
        public static final int tab_presenter_button_7_keycode_default=0x7f04008a;
        public static final int tab_presenter_button_7_modifier_default=0x7f04008b;
        public static final int tab_presenter_button_8_keycode_default=0x7f04008c;
        public static final int tab_presenter_button_8_modifier_default=0x7f04008d;
        public static final int tab_presenter_button_9_keycode_default=0x7f04008e;
        public static final int tab_presenter_button_9_modifier_default=0x7f04008f;
        public static final int tab_video_button_10_keycode_default=0x7f040078;
        public static final int tab_video_button_10_modifier_default=0x7f040079;
        public static final int tab_video_button_11_keycode_default=0x7f04007a;
        public static final int tab_video_button_11_modifier_default=0x7f04007b;
        public static final int tab_video_button_12_keycode_default=0x7f04007c;
        public static final int tab_video_button_12_modifier_default=0x7f04007d;
        /**  Default Mappings Video Tab 
         */
        public static final int tab_video_button_1_keycode_default=0x7f040066;
        public static final int tab_video_button_1_modifier_default=0x7f040067;
        public static final int tab_video_button_2_keycode_default=0x7f040068;
        public static final int tab_video_button_2_modifier_default=0x7f040069;
        public static final int tab_video_button_3_keycode_default=0x7f04006a;
        public static final int tab_video_button_3_modifier_default=0x7f04006b;
        public static final int tab_video_button_4_keycode_default=0x7f04006c;
        public static final int tab_video_button_4_modifier_default=0x7f04006d;
        public static final int tab_video_button_5_keycode_default=0x7f04006e;
        public static final int tab_video_button_5_modifier_default=0x7f04006f;
        public static final int tab_video_button_6_keycode_default=0x7f040070;
        public static final int tab_video_button_6_modifier_default=0x7f040071;
        public static final int tab_video_button_7_keycode_default=0x7f040072;
        public static final int tab_video_button_7_modifier_default=0x7f040073;
        public static final int tab_video_button_8_keycode_default=0x7f040074;
        public static final int tab_video_button_8_modifier_default=0x7f040075;
        public static final int tab_video_button_9_keycode_default=0x7f040076;
        public static final int tab_video_button_9_modifier_default=0x7f040077;
        public static final int yes=0x7f04000d;
    }
}
